FROM golang:1.24.5-alpine

RUN apk update &&\
	apk upgrade &&\
	apk add bash &&\
    apk add aws-cli

WORKDIR /app
COPY . ./

RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o job-checker ./cmd/job/checker/main.go

COPY /kube/config /root/.kube/config

CMD ["/app/job-checker"]
