FROM golang:1.25.0-alpine

RUN apk update &&\
	apk upgrade &&\
	apk add bash &&\
    apk add aws-cli

WORKDIR /app
COPY . ./

COPY .kube/config ~/.kube/config

RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o job-starter ./cmd/job/starter/main.go

CMD ["/app/job-starter"]
