apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: kube-system
type: Opaque
data:
  # Base64 encoded values - replace with your actual credentials
  # echo -n "your-elasticsearch-host" | base64
  # echo -n "your-elasticsearch-password" | base64
  host: <base64-encoded-host>
  port: <base64-encoded-port>
  username: <base64-encoded-username>
  password: <base64-encoded-password>
