apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.11.0
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9600
          name: performance-analyzer
        env:
        - name: discovery.type
          value: single-node
        - name: "OPENSEARCH_JAVA_OPTS"
          value: "-Xms256m -Xmx256m"
        - name: "plugins.security.disabled"
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: opensearch-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: observability
spec:
  selector:
    app: opensearch
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  - name: performance-analyzer
    port: 9600
    targetPort: 9600